# Sample workflow for building and deploying Discord bot
name: Deploy Discord bot to VPS

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: |
          echo "Building the project..."
          zig build --release=safe -Dtarget=x86_64-linux-gnu -Dcpu=baseline

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ergonautes_discord_bot
          path: zig-out/bin/ergonautes_discord_bot
          archive: false
          if-no-files-found: error

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ergonautes_discord_bot
          path: ./bin

      - name: Configure SSH for VPS
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/github-actions-deploy
          chmod 600 ~/.ssh/github-actions-deploy
          ssh-keyscan -p "${{ secrets.VPS_SSH_PORT }}" -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload binary to VPS
        run: |
          scp \
            -P "${{ secrets.VPS_SSH_PORT }}" \
            -i ~/.ssh/github-actions-deploy \
            ./bin/ergonautes_discord_bot \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/ergonautes_discord_bot.new

      - name: Activate deployment
        run: |
          ssh \
            -p "${{ secrets.VPS_SSH_PORT }}" \
            -i ~/.ssh/github-actions-deploy \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            'chmod +x /home/${{ secrets.VPS_USER }}/ergonautes_discord_bot.new &&
            mv /home/${{ secrets.VPS_USER }}/ergonautes_discord_bot.new /home/${{ secrets.VPS_USER }}/ergonautes_discord_bot &&
            systemctl --user restart discordbot'
